# Tuesday March 15, 2016
# Makefile
# Waheed Brown
#
# OpenGL Redbook - Chapter 2 - Example 2.4
# 
# Reference:
# Shreiner, D., et. al., "OpenGL Programming Guide, 8th Ed.", (c) 2013 Pearson Education, Inc.

linux:
	g++ CompileShader.cpp -lGLEW -lGL -lglut -o CompileShader

debug:
	g++ -g CompileShader.cpp -lGLEW -lGL -lglut -o CompileShader

clean:
	rm -rf *~
	rm -rf *~
	rm -rf CompileShader

