# Wednesday March 16, 2016
# Makefile
# Waheed Brown
#
# OpenGL Redbook - Chapter 2 - Example 2.2
# 
# Reference:
# Shreiner, D., et. al., "OpenGL Programming Guide, 8th Ed.", (c) 2013 Pearson Education, Inc.

linux:
	g++ Uniform.cpp LoadShaders.cpp -lGLEW -lGL -lglut -o Uniform

debug:
	g++ -g Uniform.cpp LoadShaders.cpp -lGLEW -lGL -lglut -o Uniform

clean:
	rm -rf *~
	rm -rf *~
	rm -rf Uniform

