# Saturday March 5, 2016
# Makefile
# Waheed Brown
#
# OpenGL Redbook - Chapter 1 - Example 1.1
# 
# Reference:
# Shreiner, D., et. al., "OpenGL Programming Guide, 8th Ed.", (c) 2013 Pearson Education, Inc.

linux:
	g++ triangles.cpp LoadShaders.cpp -lGLEW -lGL -lglut -o triangles

debug:
	g++ -g triangles.cpp LoadShaders.cpp -lGLEW -lGL -lglut -o triangles

clean:
	rm -rf *~
	rm -rf *~
	rm -rf triangles

