# Makefile
#
# 2015/12/21
# Waheed Brown
#
# OpenGL Tutorial - Quaternions
# http://www.cprogramming.com/tutorial/3d/quaternions.html

all:
	gcc quatrotation.c quaternion.c -lm -o quatrotation
debug:
	gcc -g quatrotation.c quaternion.c -lm -o quatrotation
clean:
	rm -rf *o
	rm -rf *#
	rm -rf *~
	rm -rf *dSYM
	rm -rf quatrotation

