# Makefile
#
# 2015/12/21
# Waheed Brown
#
# OpenGL Tutorial - Quaternions
# http://www.cprogramming.com/tutorial/3d/quaternions.html

all:
	g++ quatrotation.cpp quaternion.cpp -o quatrotation
debug:
	g++ -g quatrotation.cpp quaternion.cpp -o quatrotation
clean:
	rm -rf *o
	rm -rf *#
	rm -rf *~
	rm -rf *dSYM
	rm -rf quatrotation

