# Sunday December 27, 2015
#
# Makefile
# Waheed Brown
#
# OpenGL Setup:
# http://www.codeproject.com/Articles/182109/Setting-up-an-OpenGL-development-environment-in-Ub

linux:
	g++ firstwindow.cpp -lGL -lGLU -lglut -o firstwindow

clean:
	rm -rf *~
	rm -rf *#
	rm -rf *~
	rm -rf *dSYM
	rm -rf firstwindow

